spring:    
  datasource:
    url: jdbc:mysql://localhost:3306/public?schema=public
    username: root
    password: Giuliahj_162607
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: user-management
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 8080
  error:
    include-stacktrace: on-param